// apps/web/components/ui/empty-state.tsx
import type { ReactNode } from "react";
import { cn } from "@/lib/utils";

export function EmptyState({
  icon,
  title,
  description,
  action,
  className,
}: {
  icon?: ReactNode;
  title: string;
  description?: string;
  action?: ReactNode;
  className?: string;
}) {
  return (
    <div
      className={cn(
        "flex flex-col items-center justify-center rounded-2xl border border-dashed border-border/80 bg-muted/20 px-cg-6 py-cg-8 text-center",
        className,
      )}
    >
      {icon ? <div className="mb-cg-4 text-muted-foreground">{icon}</div> : null}
      <p className="text-ds-h3 font-semibold text-foreground">{title}</p>
      {description ? <p className="mt-cg-2 max-w-md text-ds-body text-muted-foreground">{description}</p> : null}
      {action ? <div className="mt-cg-5">{action}</div> : null}
    </div>
  );
}

// frontend/ClinicSaaS.Web/src/app/core/empty-state.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';

@Component({
  selector: 'app-empty-state, mc-empty',
  standalone: true,
  template: `
    <div class="ui-empty mc-space-panel">
      <div class="mx-auto mb-2 flex h-10 w-10 items-center justify-center rounded-full border border-white/15 bg-white/5 text-slate-300">
        {{ icon }}
      </div>
      <div class="mc-text-body font-semibold text-slate-100">{{ title }}</div>
      <div class="mt-1 mc-text-small text-slate-400">{{ description }}</div>
      @if (ctaLabel) {
        <button type="button" class="mc-signal-cta mt-3" (click)="cta.emit()">{{ ctaLabel }}</button>
      }
    </div>
  `,
})
export class EmptyStateComponent {
  @Input() icon = '○';
  @Input({ required: true }) title = '';
  @Input({ required: true }) description = '';
  @Input() ctaLabel = '';
  @Output() cta = new EventEmitter<void>();
}
